Script con la creación de tablas (S_ORDERS_CLEAN, S_CLEANED_TRANSFORMED, S_PAYMENT_METHODS)

CREATE OR REPLACE TABLE S_ORDERS_CLEAN (
  ID_ORDER STRING,
  DTE_ORDER DATE,
  ID_CUSTOMER STRING,
  ID_PART STRING,
  QTY_ORDERED NUMBER,
  AMT_TOTAL NUMBER(10,2),
  REF_PAYMENT_METHOD STRING,
  DTE_DELIVERY_EST DATE,
  DES_ORDER_NOTE STRING
);

CREATE OR REPLACE TABLE S_CLEANED_TRANSFORMED AS
SELECT
  ID_ORDER,
  TRY_TO_DATE(DTE_ORDER, 'YYYY-MM-DD') AS DTE_ORDER,
  ID_CUSTOMER,
  ID_PART,
  CASE 
    WHEN TRY_TO_NUMBER(QTY_ORDERED) IS NOT NULL AND TRY_TO_NUMBER(QTY_ORDERED) > 0 THEN TRY_TO_NUMBER(QTY_ORDERED)
    ELSE NULL 
  END AS QTY_ORDERED,
  TRY_TO_NUMBER(AMT_TOTAL) AS AMT_TOTAL,
  UPPER(REF_PAYMENT_METHOD) AS REF_PAYMENT_METHOD,
  TRY_TO_DATE(DTE_DELIVERY_EST, 'YYYY-MM-DD') AS DTE_DELIVERY_EST,
  DES_ORDER_NOTE
FROM B_ORDERS_RAW_COMPLEX;

   -- Crear tabla de métodos de pago
CREATE OR REPLACE TABLE S_PAYMENT_METHODS (
  REF_PAYMENT_METHOD STRING PRIMARY KEY,
  DES_PAYMENT_METHOD STRING
);

